apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: ventress10-ns
  namespace: openshift-gitops
spec:
  destination:
    namespace: ventress10
    server: https://kubernetes.default.svc
  project: ventress10
  source:
    path: lab3-4/env/overlays
    repoURL: https://github.com//eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
